sync with main repo

diff --git a/0initrd/sbin/probedisk b/0initrd/sbin/probedisk
--- a/0initrd/sbin/probedisk
+++ b/0initrd/sbin/probedisk
@@ -3,7 +3,6 @@
 #based on probedisk3 written by Dougal.
 # 21 Jun 2007 BK: force /proc update for usb drives.
 #v3.93 10 dec 2007 BK: updated for 2.6.24 kernel, no /dev/hd*.
-#v406 support for old kernel, /proc/ide, /dev/hd*.
 
 ## MMC - SD cards
 #  Some laptops with built in SD card readers report SD cards as /dev/sd* and usb
@@ -73,8 +72,6 @@ if [ "$HR_SIZE" = "yes" -a "$SPECIFIC" = "" ] ; then
 	PLUS_SIZE=yes
 fi
 
-device=${@##*/}
-
 #==============================================================
 #                        FUNCTIONS
 #==============================================================
@@ -93,42 +90,23 @@ hdparm_get_model() {
 	done
 }
 
-# $1: drv
+# $1: drvname
 do_probedisk() {
 
-	[ "$1" ] || return 1
-	DRV=${1##*/} #basename
-
-	if [ ! -e /sys/block/${DRV} ] ; then
-		echo "${DRV}: invalid drive" 1>&2
-		continue
-	fi
+	DRV=$1
 
 	vendor=""
 	model=""
 	size=""
 	removable=""
 	usb=""
-	xtype=""
 
 	blockdev=/dev/${DRV}
-	[ -e /dev/block/${DRV} ] && blockdev=/dev/block/${DRV} #android
-
-	case $(readlink /sys/block/${DRV}) in */usb*)
-		usb=yes
-		#force /proc upate mechanism
-		#dd if=${blockdev} of=/dev/null bs=512 count=1 1>/dev/null 2>&1
-		;;
-	esac
 
 	[ -f /sys/block/${DRV}/device/vendor ] && read -r vendor < /sys/block/${DRV}/device/vendor
 	[ -f /sys/block/${DRV}/device/model ] && read -r model < /sys/block/${DRV}/device/model
 	[ -f /sys/block/${DRV}/size ] && read -r size < /sys/block/${DRV}/size
 	[ -f /sys/block/${DRV}/removable ] && read -r removable < /sys/block/${DRV}/removable
-	blockdev=/dev/${DRV}
-	#Android
-	[ -f /sys/block/${DRV}/device/name ] && read -r name < /sys/block/${DRV}/device/name
-	[ -f /sys/block/${DRV}/device/date ] && read -r date < /sys/block/${DRV}/device/date
 
 	info="$vendor"
 	[ -n "$model" ] && info="$info $model"
@@ -136,19 +114,30 @@ do_probedisk() {
 	[ -n "$date" ] && info="$info $date"
 
 	type=drive #default
+
+	case $(readlink /sys/block/${DRV}) in */usb*)
+		type="usbdrv"
+		usb=yes ;;
+	esac
+
 	if [ -e /sys/block/${DRV}/device/type ] ; then
 		# http://lxr.free-electrons.com/source/include/scsi/scsi.h?v=3.12
 		read -r xtype < /sys/block/${DRV}/device/type
-		case $xtype in
-			0) [ "$usb" = "yes" ] && type="usbdrv" ;; #define TYPE_DISK 0x00
-			5) type='optical' ;; #define TYPE_ROM 0x05 //see below
-			MMC) info="MMC${info}" ;; #android
-			SD) info="SD${info}" ;; #android
-		esac
+		if [ "$xtype" = "5" ] ; then
+			if [ -e /sys/block/${DRV}/device/rev ] ; then
+				read rev < /sys/block/${DRV}/device/rev
+				info="$info [Rev $rev]"
+			fi
+			type='optical'
+		fi
 	fi
 
 	case ${DRV} in
-		fd*)  type=floppy  ;;
+		fd*)
+			# might be a "fake" floppy device. have to check..
+			[ "$model" = "" -a "$vendor" = "" ] && return
+			type=floppy
+			;;
 		mmc*)
 			type=card
 			if [ "$SHOW_USBFLASH" = "yes" -a "$CARD_AS_USBFLASH" = "yes" ] ; then
@@ -156,46 +145,6 @@ do_probedisk() {
 			fi
 			;;
 	esac
-
-	# -- legacy: /proc/ide - special case
-	if [ -e /proc/ide ] ; then
-		media=""
-		[ -f /proc/ide/${DRV}/model ] && read -r info < /proc/ide/${DRV}/model
-		[ -f /proc/ide/${DRV}/media ] && read -r media < /proc/ide/${DRV}/media
-		if [ "$media" = "cdrom" ] ; then
-			type=optical
-		else
-			case ${DRV} in
-				# $xtype is always set for sd*, even in very old kernels..
-				sd*) usb=yes type=usbdrv ;; # usb hd drives and usb flash drives appear as sdX
-				hd*) [ "$removable" = "1" ] && type=floppy ;; # a zip drv? https://ubuntuforums.org/showthread.php?t=1607383
-			esac
-		fi
-	fi
-	# --
-
-	if [ "$type" = "optical" ] ; then
-		if [ -e /sys/block/${DRV}/device/rev ] ; then
-			read rev < /sys/block/${DRV}/device/rev
-			info="$info [Rev $rev]"
-		fi
-	fi
-
-	## -- legacy: properly identify a floppy
-	if [ "$type" = "usbdrv" ] ; then
-		# find out if a usb floppy drive...
-		[ "$size" = "2880" ] && type=floppy
-		# if the floppy diskette not inserted, try this fallback test...
-		# some examples: Vendor: NEC Model: USB UF000x Rev: 1.50, Sony USB Floppy Drive, rev 1.10/5.01,
-		# MITUMI USB FDD, VenDor: TEAC Model: FD-05PUB, Vendor: COMPAQ Model: USB EXT FLOPPY
-		case "$model" in *" FDD"*|*" UF000x"*|*"Floppy"*|*"USB-FDU"*|"FD-"*|*"FLOPPY"*) type=floppy ;; esac
-	else
-		# find out if it is a removable internal drive (zip, ls120, etc)...
-		case ${DRV} in sd*) [ "$removable" = "1" ] && type=floppy ;; esac
-	fi
-	# might be a "fake" floppy device. have to check..
-	[ "$type" = "floppy" -a "$model" = "" -a "$vendor" = "" ] && continue
-	# --
 
 	case $type in drive|usbdrive) # -hdparm
 		if [ "$HDPARM" = "yes" -a "$removable" != "1" ] ; then
@@ -241,7 +190,13 @@ do_probedisk_all() {
 #                          MAIN
 #==============================================================
 
+device=${@##*/}
+
 if [ "$device" ] ; then
+	if [ ! -e /sys/block/${device} ] ; then
+		echo "${device}: invalid drive" 1>&2
+		exit 1
+	fi
 	do_probedisk ${device} #process cli argument
 else
 	do_probedisk_all
